# Generated by Django 6.0.4 on 2026-04-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department_head',
        ),
        migrations.RemoveField(
            model_name='team',
            name='development_focus',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jira_project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.person'),
            preserve_default=False,
        ),
    ]
