# Generated by Django 5.2.13 on 2026-05-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_department_department_head_person_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('dependency_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='dashboard.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='dashboard.team')),
            ],
            options={
                'verbose_name_plural': 'Team Dependencies',
            },
        ),
    ]
