# Generated by Django 5.2.13 on 2026-05-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_person_photo_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='extra_members', to='dashboard.team'),
        ),
    ]
