# Generated by Django 5.2.13 on 2026-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_person_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='background',
            field=models.CharField(choices=[('default', 'Default'), ('black', 'Black')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='language',
            field=models.CharField(default='English UK', max_length=50),
        ),
    ]
